function getHouse(i) {
	switch (i) {
		case 0:
			return {
				"houseId": 1,
				"ownerId": 0,
				"ownerName": "Kostas Kolivas",
				"latitude": 37.966515,
				"longitude": 23.654946,
				"address": "Ilossou 16, 18450 Nikea, Greece",
				"city": "Nikea",
				"country": "Greece",
				"numBeds": 3,
				"numBaths": 4,
				"accommodates": 4,
				"livingRoom": true,
				"smoking": false,
				"pets": true,
				"wifi": true,
				"airconditioning": true,
				"heating": true,
				"kitchen": false,
				"tv": false,
				"parking": false,
				"elevator": false,
				"events": true,
				"area": 145.4,
				"description": "This is the first house",
				"minDays": 4,
				"instructions": "Take a bus",
				"rating": 3.5,
				"numRatings": 5,
				"dateFrom": "2017-08-05",
				"dateTo": "2017-09-10",
				"minCost": 150,
				"costPerPerson": 15,
				"pictures": ["pics/pic1.jpeg"]
			}
		case 1:
			return {
				"houseId": 2,
				"onwerId": 1,
				"ownerName": "Erika Koliva",
				"latitude": 37.966515,
				"longitude": 23.654946,
				"address": "Ilossou 16, 18450 Nikea, Greece",
				"city": "Nikea",
				"country": "Greece",
				"numBeds": 2,
				"numBaths": 1,
				"accommodates": 2,
				"livingRoom": false,
				"smoking": true,
				"pets": false,
				"wifi": true,
				"airconditioning": true,
				"heating": true,
				"kitchen": true,
				"tv": true,
				"parking": false,
				"elevator": false,
				"events": false,
				"area": 145.4,
				"description": "This is the second house",
				"minDays": 4,
				"instructions": "Take a bus",
				"rating": 2,
				"numRatings": 10,
				"dateFrom": "2017-08-02",
				"dateTo": "2017-09-11",
				"minCost": 140,
				"costPerPerson": 15,
				"pictures": ["pics/pic2.jpeg"]

			}
		case 2:
			return {
				"houseId": 3,
				"ownerId": 0,
				"ownerName": "Kostas Kolivas",
				"latitude": 37.966515,
				"longitude": 23.654946,
				"address": "Ilossou 16, 18450 Nikea, Greece",
				"city": "Nikea",
				"country": "Greece",
				"numBeds": 6,
				"numBaths": 3,
				"accommodates": 7,
				"livingRoom": true,
				"smoking": false,
				"pets": false,
				"wifi": true,
				"airconditioning": true,
				"heating": true,
				"kitchen": true,
				"tv": true,
				"parking": true,
				"elevator": false,
				"events": false,
				"area": 169.4,
				"description": "This is the third house",
				"minDays": 5,
				"instructions": "Take a bus",
				"rating": 4.5,
				"numRatings": 500,
				"dateFrom": "2017-08-01",
				"dateTo": "2017-12-01",
				"minCost": 450,
				"costPerPerson": 30,
				"pictures": ["pics/pic3.jpeg"]

			}
		case 3:
			return {
				"houseId": 3,
				"ownerId": 2,
				"ownerName": "Mimi Demy",
				"latitude": 37.966515,
				"longitude": 23.654946,
				"address": "Ilossou 16, 18450 Nikea, Greece",
				"city": "Nikea",
				"country": "Greece",
				"numBeds": 3,
				"numBaths": 1,
				"accommodates": 3,
				"livingRoom": false,
				"smoking": true,
				"pets": true,
				"wifi": false,
				"airconditioning": true,
				"heating": true,
				"kitchen": false,
				"tv": false,
				"parking": false,
				"elevator": true,
				"events": true,
				"area": 54,
				"description": "This is the fourth house",
				"minDays": 0,
				"instructions": "Take a bus",
				"rating": 2.3,
				"numRatings": 100,
				"dateFrom": "2017-07-02",
				"dateTo": "2017-14-02",
				"minCost": 450,
				"costPerPerson": 30,
				"pictures": ["pics/pic4.jpeg"]
			}
		case 4:
			return {
				"houseId": 4,
				"ownerId": 0,
				"ownerName": "Kostas Kolivas",
				"latitude": 37.966515,
				"longitude": 23.654946,
				"address": "Ilossou 16, 18450 Nikea, Greece",
				"city": "Nikea",
				"country": "Greece",
				"numBeds": 1,
				"numBaths": 1,
				"accommodates": 1,
				"livingRoom": false,
				"smoking": true,
				"pets": true,
				"wifi": true,
				"airconditioning": false,
				"heating": true,
				"kitchen": true,
				"tv": true,
				"parking": false,
				"elevator": true,
				"events": true,
				"area": 54,
				"description": "This is the fifth house",
				"minDays": 2,
				"instructions": "Take a bus",
				"rating": 2.3,
				"numRatings": 100,
				"dateFrom": "2017-07-02",
				"dateTo": "2017-14-02",
				"minCost": 15,
				"costPerPerson": 10,
				"pictures": ["pics/pic5.jpeg"]
			}
		default:
			return null;
	}
}

function getHouseMin(i) {
	var tmp = getHouse(i)
	if (tmp == null) return null;
	return new HouseMin(
		tmp.houseId,
        tmp.city,
        tmp.country,
        tmp.rating,
        tmp.numRatings,
        tmp.minCost,
        tmp.pictures[0]
	);
}